---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guac-data0
  namespace: guac
  labels:
    app: guac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
