---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac
  namespace: guac
  labels:
    app: guac
spec:
  selector:
    matchLabels:
      app: guac
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guac
    spec:
      containers:
        - name: guac
          image: oznu/guacamole
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: America/Chicago
          #        - name: EXTENSIONS
          #          value: auth-totp
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          volumeMounts:
            - mountPath: /config
              name: guac-data0
      volumes:
        - name: guac-data0
          persistentVolumeClaim:
            claimName: guac-data0
