---
apiVersion: v1
kind: Service
metadata:
  name: guac
  namespace: guac
  labels:
    app: guac
spec:
  ports:
    - name: guac-port
      port: 8080
      # targetPort: 8080
  selector:
    app: guac
  # type: LoadBalancer
